language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache/files

matrix:
  include:
    - php: 5.6
      env: deps=low
    - php: hhvm
      env: deps=low
    - php: 7.0
      env: deps=low
    - php: 5.6
    - php: hhvm
    - php: 7.0
  fast_finish: true

install:
  - composer self-update -q
  - if [ "$deps" = "no" ]; then composer --prefer-stable --prefer-dist -n update; fi;
  - if [ "$deps" = "low" ]; then composer --prefer-lowest -n --prefer-stable --prefer-dist update; fi;

env:
  global:
    - SYMFONY_DEPRECATIONS_HELPER=strict
    - deps=no

script:
  ./vendor/bin/phpunit

branches:
  except:
    - /^feat.*/
    - /^bug.*/
    - /^fix.*/
