services:
    swagger.validator_map:
        class: Nicofuma\SwaggerBundle\Validator\ValidatorMap
        arguments:
          - '@service_container'
          - [] # Validator's array map

    swagger.validator:
        class: Nicofuma\SwaggerBundle\Validator\Validator
        abstract: true
        arguments:
          - ~ # SchemaManager
          - ~ # Strict

    swagger.schema_manager_factory:
        class: Nicofuma\SwaggerBundle\Swagger\SchemaManagerFactory
        arguments:
          - '@kernel'

    swagger.schema_manager:
        class: FR3D\SwaggerAssertions\SchemaManager
        abstract: true
        factory: ['@swagger.schema_manager_factory', createFromFile]
        arguments:
          - ~ # SwaggerFile

    swagger.validator_listener:
        class: Nicofuma\SwaggerBundle\EventListener\ValidatorListener
        arguments:
          - '@swagger.validator_map'
        tags:
          - { name: kernel.event_subscriber }

    bootstrap.fos_rest.request.param_fetcher:
        class: Nicofuma\SwaggerBundle\FosRest\ParamFetcher
        arguments:
          - ~ # Inner service
          - '@swagger.validator_map'
          - '@request_stack'
